// React_composant/Commande/src/app/components/Dashboard.tsx
import { useState } from "react";
import svgPaths from "../../imports/svg-n78j0upy1w";
import imgPhotoDeProfil1 from "figma:asset/5e48039e7a6e82730827415ea7f62a4505d0384f.png";
import imgGeminiGeneratedImageCsgywdcsgywdcsgyRemovebgPreview11 from "figma:asset/74db711eeaa4dd300307a93d2f91d234fe25479c.png";
import imgGeminiGeneratedImageKughr6Kughr6KughRemovebgPreview1 from "figma:asset/0112e96aeef9cd395e0ac5b324f868a6b2ebc070.png";
import imgGeminiGeneratedImageMg6Zgmg6Zgmg6ZgmRemovebgPreview1 from "figma:asset/d4d04f74b1afb302ab56eb97b07c099916e2a363.png";
import imgGeminiGeneratedImageXeeemjxeeemjxeeeRemovebgPreview1 from "figma:asset/bf96c447d81a166d68c26134eb659adeb2a627a5.png";
import imgGeminiGeneratedImageXjtvvixjtvvixjtvRemovebgPreview1 from "figma:asset/4a62353ebd8b7ec036d8e8d5f6bfcb7a7674138f.png";
import imgGeminiGeneratedImage2Zg7Ak2Zg7Ak2Zg7RemovebgPreview1 from "figma:asset/838d00d1474b055a2b733396a77bf3adb3da9229.png";

// Types
export interface DashboardData {
  revenue: {
    value: string;
    change: string;
    period: string;
  };
  pharmacies: {
    value: number;
    subtitle: string;
    change: string;
    period: string;
  };
  orders: {
    value: number;
    unit: string;
    change: string;
    period: string;
  };
  patients: {
    value: number;
    subtitle: string;
    change: string;
    period: string;
  };
  pharmacyOrders?: Array<{ name: string; value: number }>;
  zoneDistribution?: Array<{ name: string; percentage: string; color: string }>;
  userName?: string;
  userRole?: string;
}

const defaultData: DashboardData = {
  revenue: {
    value: "100000",
    change: "+2.5%",
    period: "Depuis cette semaine",
  },
  pharmacies: {
    value: 10,
    subtitle: "Pharmacies de Jour",
    change: "+2.5%",
    period: "Depuis cette semaine",
  },
  orders: {
    value: 300,
    unit: "cmd",
    change: "+2.5%",
    period: "Depuis cette semaine",
  },
  patients: {
    value: 38,
    subtitle: "Depuis cette semaine",
    change: "+2.5%",
    period: "Depuis cette semaine",
  },
  pharmacyOrders: [
    { name: "RenandeetMaat", value: 50 },
    { name: "Vander Veecken", value: 15 },
    { name: "Bet'leem", value: 25 },
    { name: "Clairon", value: 15 },
    { name: "Cristale", value: 20 },
    { name: "Jagger", value: 45 },
  ],
  zoneDistribution: [
    { name: "Moungali", percentage: "38%", color: "#3995D2" },
    { name: "Poto-Poto", percentage: "30%", color: "#DC3545" },
    { name: "Bacongo", percentage: "18%", color: "#FD7E14" },
    { name: "Makélékélé", percentage: "23%", color: "#FFC107" },
    { name: "Ouenzé", percentage: "15%", color: "#198754" },
    { name: "Mfilou", percentage: "15%", color: "#6610F2" },
  ],
  userName: "Merc Mig's",
  userRole: "Admin",
};

export interface DashboardProps {
  data?: DashboardData;
  onNavigate?: (page: string) => void;
}

function BackgroundColor() {
  return (
    <div
      className="absolute blur-[50px] h-[1140px] left-0 opacity-82 top-0 w-[1800px]"
      data-name="background_color"
      style={{
        backgroundImage:
          "linear-gradient(60.0211deg, rgb(57, 149, 210) 35.89%, rgb(91, 182, 110) 92.848%)",
      }}
    />
  );
}

// Logo BengaDok
function LogoBengaDok() {
  return (
    <div className="flex items-center gap-2">
      <div className="size-[40px] bg-white rounded-full flex items-center justify-center">
        <svg width="32" height="32" viewBox="0 0 32 32" fill="none">
          <circle cx="16" cy="16" r="14" fill="#3995D2" />
          <path
            d="M16 8C12.7 8 10 10.7 10 14C10 17.3 12.7 20 16 20C19.3 20 22 17.3 22 14C22 10.7 19.3 8 16 8ZM16 18C13.8 18 12 16.2 12 14C12 11.8 13.8 10 16 10C18.2 10 20 11.8 20 14C20 16.2 18.2 18 16 18Z"
            fill="white"
          />
          <path d="M16 12C14.9 12 14 12.9 14 14C14 15.1 14.9 16 16 16C17.1 16 18 15.1 18 14C18 12.9 17.1 12 16 12Z" fill="white" />
        </svg>
      </div>
      <div>
        <span className="text-[#3995D2] font-bold text-[18px]">Benga</span>
        <span className="text-[#5BB66E] font-bold text-[18px]">Dok</span>
      </div>
    </div>
  );
}

// Menu items
function MenuItem({ icon, label, active, onClick }: { icon: string; label: string; active?: boolean; onClick?: () => void }) {
  // Safely access the SVG path
  const pathData = (svgPaths as any)[icon] || "";
  
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-3 w-full px-3 py-2 rounded-lg transition-all ${
        active ? "bg-gray-900 text-white" : "text-gray-700 hover:bg-gray-100"
      }`}
    >
      <div className={`size-[36px] rounded-full flex items-center justify-center ${active ? "bg-white/20" : "bg-[rgba(92,89,89,0.25)]"}`}>
        <svg className="size-[24px]" fill="none" viewBox="0 0 24 24">
          {pathData && <path d={pathData} fill={active ? "white" : "#5C5959"} />}
        </svg>
      </div>
      <span className="text-[14px] font-medium">{label}</span>
    </button>
  );
}

// Sidebar
function Sidebar({ userName, userRole, onNavigate }: { userName?: string; userRole?: string; onNavigate?: (page: string) => void }) {
  const [activePage, setActivePage] = useState("dashboard");

  const handleNavigation = (page: string) => {
    setActivePage(page);
    onNavigate?.(page);
  };

  return (
    <div className="bg-white h-screen w-[200px] shadow-lg flex flex-col relative overflow-hidden">
      {/* Images décoratives en bas */}
      <div className="absolute flex items-center justify-center left-[-65px] size-[224.514px] top-[653px]">
        <div className="flex-none rotate-[-17.3deg]">
          <div className="relative shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] size-[179.301px]">
            <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImageKughr6Kughr6KughRemovebgPreview1} />
          </div>
        </div>
      </div>
      <div className="absolute flex items-center justify-center left-[175.85px] size-[139.423px] top-[663.48px]">
        <div className="flex-none rotate-[9.83deg]">
          <div className="relative shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] size-[120.603px]">
            <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImageMg6Zgmg6Zgmg6ZgmRemovebgPreview1} />
          </div>
        </div>
      </div>
      <div className="absolute flex items-center justify-center left-[67px] size-[199.398px] top-[663px]">
        <div className="flex-none rotate-[26.65deg]">
          <div className="relative shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] size-[148.546px]">
            <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImageXeeemjxeeemjxeeeRemovebgPreview1} />
          </div>
        </div>
      </div>
      <div className="absolute flex items-center justify-center left-[188px] size-[200.961px] top-[703px]">
        <div className="flex-none rotate-[12.62deg]">
          <div className="relative shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] size-[168.256px]">
            <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImageXjtvvixjtvvixjtvRemovebgPreview1} />
          </div>
        </div>
      </div>

      {/* Logo */}
      <div className="p-4 border-b border-gray-200 relative z-10">
        <LogoBengaDok />
      </div>

      {/* Menu items */}
      <nav className="flex-1 p-3 space-y-2 relative z-10">
        <MenuItem icon="p316d1680" label="Tableau de bord" active={activePage === "dashboard"} onClick={() => handleNavigation("dashboard")} />
        <MenuItem icon="p85d1500" label="Commandes" active={activePage === "orders"} onClick={() => handleNavigation("orders")} />
        <MenuItem icon="p35691900" label="Pharmacies" active={activePage === "pharmacies"} onClick={() => handleNavigation("pharmacies")} />
        <MenuItem icon="p20e2ed00" label="Médicaments" active={activePage === "medications"} onClick={() => handleNavigation("medications")} />
        <MenuItem icon="p214df580" label="Clients" active={activePage === "clients"} onClick={() => handleNavigation("clients")} />
        <MenuItem icon="p11af0b00" label="Utilisateurs Backoffice" active={activePage === "users"} onClick={() => handleNavigation("users")} />
      </nav>

      {/* Réglages et Déconnexion */}
      <div className="p-3 border-t border-gray-200 space-y-2 relative z-10">
        <MenuItem icon="pab73400" label="Réglages" onClick={() => handleNavigation("settings")} />
        
        {/* Illustration de déconnexion */}
        <div className="relative h-[200px] -mx-3 -mb-3">
          <div className="absolute h-[337.066px] left-[10px] top-[20px] w-[180px]">
            <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImage2Zg7Ak2Zg7Ak2Zg7RemovebgPreview1} />
          </div>
          <button className="absolute bottom-4 left-1/2 -translate-x-1/2 bg-[#5c5959] text-white px-4 py-2 rounded-full text-[12px] font-medium hover:bg-[#4a4747] transition-colors flex items-center gap-2 z-10">
            <svg className="size-[18px]" fill="none" viewBox="0 0 24 24">
              <path d={(svgPaths as any).p3089d000 || ""} fill="white" />
            </svg>
            Déconnexion
          </button>
        </div>
      </div>
    </div>
  );
}

// Stat Card
function StatCard({ title, value, subtitle, change, period }: { title: string; value: string; subtitle?: string; change: string; period: string }) {
  const svgData = (svgPaths as any).p17d7cb00 || "";
  
  return (
    <div className="bg-white rounded-[20px] shadow-lg p-6 relative overflow-hidden">
      <h3 className="text-[14px] font-bold text-gray-900 mb-2">{title}</h3>
      <div className="flex items-baseline gap-2 mb-1">
        <span className="text-[32px] font-bold text-gray-900">{value}</span>
        {subtitle && <span className="text-[12px] text-gray-600">{subtitle}</span>}
      </div>
      <div className="flex items-center gap-2 text-[10px]">
        <span className="text-green-600 flex items-center gap-1">
          <svg width="12" height="10" viewBox="0 0 12 10" fill="none">
            {svgData && <path d={svgData} fill="#198754" />}
          </svg>
          {change}
        </span>
        <span className="text-gray-500">{period}</span>
      </div>
    </div>
  );
}

// Bar Chart pour pharmacies
function PharmacyBarChart({ data }: { data: Array<{ name: string; value: number }> }) {
  const maxValue = Math.max(...data.map((d) => d.value));
  const dropdownSvg = (svgPaths as any).p1da9a000 || "";

  return (
    <div className="bg-white rounded-[30px] shadow-lg p-6">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-[16px] font-bold text-gray-900">Volume commandes par pharmacies</h3>
        <button className="border border-black rounded-[13px] px-3 py-1 text-[14px] flex items-center gap-1">
          Ce mois
          <svg width="9" height="5" viewBox="0 0 9 5" fill="none">
            {dropdownSvg && <path d={dropdownSvg} fill="black" />}
          </svg>
        </button>
      </div>

      <div className="relative h-[300px] flex items-end justify-around gap-4 px-4">
        {/* Y-axis labels */}
        <div className="absolute left-0 top-0 bottom-8 flex flex-col justify-between text-[12px] text-gray-600">
          <span>50</span>
          <span>35</span>
          <span>30</span>
          <span>25</span>
          <span>20</span>
          <span>15</span>
          <span>10</span>
          <span>5</span>
        </div>

        {/* Bars */}
        <div className="flex-1 flex items-end justify-around gap-3 ml-8">
          {data.map((item, index) => (
            <div key={index} className="flex flex-col items-center flex-1">
              <div
                className="bg-[#5bb66e] w-full rounded-t-[3px] transition-all hover:bg-[#4ca55d]"
                style={{ height: `${(item.value / maxValue) * 250}px` }}
              />
              <span className="text-[10px] text-gray-700 mt-2 text-center whitespace-nowrap">{item.name}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// Pie Chart pour zones
function ZonePieChart({ data }: { data: Array<{ name: string; percentage: string; color: string }> }) {
  let currentAngle = 0;
  const dropdownSvg = (svgPaths as any).p1da9a000 || "";

  const slices = data.map((item) => {
    const percentage = parseFloat(item.percentage);
    const angle = (percentage / 100) * 360;
    const startAngle = currentAngle;
    currentAngle += angle;
    return { ...item, startAngle, angle, percentage };
  });

  return (
    <div className="bg-white rounded-[30px] shadow-lg p-6">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-[16px] font-bold text-gray-900">Volume commandes par zone</h3>
        <button className="border border-black rounded-[13px] px-3 py-1 text-[14px] flex items-center gap-1">
          Ce mois
          <svg width="9" height="5" viewBox="0 0 9 5" fill="none">
            {dropdownSvg && <path d={dropdownSvg} fill="black" />}
          </svg>
        </button>
      </div>

      <div className="flex items-center justify-center gap-8">
        {/* Pie chart */}
        <div className="relative size-[250px]">
          <svg viewBox="0 0 200 200" className="size-full -rotate-90">
            {slices.map((slice, index) => {
              const radius = 80;
              const cx = 100;
              const cy = 100;
              const startAngle = (slice.startAngle * Math.PI) / 180;
              const endAngle = ((slice.startAngle + slice.angle) * Math.PI) / 180;

              const x1 = cx + radius * Math.cos(startAngle);
              const y1 = cy + radius * Math.sin(startAngle);
              const x2 = cx + radius * Math.cos(endAngle);
              const y2 = cy + radius * Math.sin(endAngle);

              const largeArcFlag = slice.angle > 180 ? 1 : 0;

              return (
                <path
                  key={index}
                  d={`M ${cx} ${cy} L ${x1} ${y1} A ${radius} ${radius} 0 ${largeArcFlag} 1 ${x2} ${y2} Z`}
                  fill={slice.color}
                  className="hover:opacity-80 transition-opacity"
                />
              );
            })}
          </svg>
          
          {/* Center icon */}
          <div className="absolute inset-0 flex items-center justify-center">
            <div className="size-[80px] bg-white rounded-full flex items-center justify-center">
              <img src={imgGeminiGeneratedImageCsgywdcsgywdcsgyRemovebgPreview11} alt="" className="size-[60px] object-contain" />
            </div>
          </div>
        </div>

        {/* Legend */}
        <div className="space-y-3">
          {data.map((item, index) => (
            <div key={index} className="flex items-center gap-3">
              <div className="size-[12px] rounded-sm" style={{ backgroundColor: item.color }} />
              <span className="text-[14px] font-bold" style={{ color: item.color }}>
                {item.name}
              </span>
              <span className="text-[14px] text-gray-600 ml-auto">{item.percentage}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

export function Dashboard({ data = defaultData, onNavigate }: DashboardProps = {}) {
  return (
    <div className="bg-white relative size-full flex" data-name="dashboard">
      <BackgroundColor />

      {/* Sidebar */}
      <Sidebar userName={data.userName} userRole={data.userRole} onNavigate={onNavigate} />

      {/* Main content */}
      <main className="flex-1 overflow-y-auto p-8 relative z-10">
        {/* Header avec user */}
        <div className="flex items-center justify-end gap-4 mb-6">
          <button className="size-[40px] bg-white rounded-full flex items-center justify-center shadow-md hover:shadow-lg transition-shadow relative">
            <svg className="size-[20px]" fill="none" viewBox="0 0 24 24">
              <path d={svgPaths.p25e39680} fill="#5C5959" />
            </svg>
            <div className="absolute top-0 right-0 size-[12px] bg-red-500 rounded-full border-2 border-white" />
          </button>
          <div className="flex items-center gap-2 bg-white rounded-full shadow-md px-3 py-2">
            <div className="size-[32px] rounded-full overflow-hidden">
              <img src={imgPhotoDeProfil1} alt={data.userName} className="size-full object-cover" />
            </div>
            <div className="text-right">
              <p className="text-[12px] font-bold text-gray-900">{data.userName}</p>
              <p className="text-[10px] text-gray-600">{data.userRole}</p>
            </div>
            <svg className="size-[16px]" fill="none" viewBox="0 0 17 11">
              <path d={svgPaths.p15992980} fill="#5C5959" />
            </svg>
          </div>
        </div>

        {/* Hero section */}
        <div className="bg-white rounded-[30px] shadow-lg p-8 mb-6 relative overflow-hidden">
          {/* Icônes décoratives */}
          <div className="absolute flex items-center justify-center left-[586px] size-[178.042px] top-[-57px]">
            <div className="flex-none rotate-[3.55deg]">
              <div className="relative shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] size-[167.956px]">
                <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImageCsgywdcsgywdcsgyRemovebgPreview11} />
              </div>
            </div>
          </div>
          <div className="absolute flex items-center justify-center left-[947.51px] size-[224.514px] top-px">
            <div className="flex-none rotate-[-17.3deg]">
              <div className="relative shadow-[0px_4px_4px_0px_rgba(0,0,0,0.25)] size-[179.301px]">
                <img alt="" className="absolute inset-0 max-w-none object-cover pointer-events-none size-full" src={imgGeminiGeneratedImageKughr6Kughr6KughRemovebgPreview1} />
              </div>
            </div>
          </div>

          <h1 className="text-[40px] font-bold text-[#5c5959] leading-tight max-w-[450px] relative z-10">
            Toutes les données au même endroit
          </h1>
        </div>

        {/* Stats cards */}
        <div className="grid grid-cols-4 gap-4 mb-6">
          <StatCard
            title="Revenus Total Comission"
            value={data.revenue.value}
            subtitle="XAF"
            change={data.revenue.change}
            period={data.revenue.period}
          />
          <StatCard
            title="Pharmacies"
            value={data.pharmacies.value.toString()}
            subtitle={data.pharmacies.subtitle}
            change={data.pharmacies.change}
            period={data.pharmacies.period}
          />
          <StatCard
            title="Commandes Total"
            value={data.orders.value.toString()}
            subtitle={data.orders.unit}
            change={data.orders.change}
            period={data.orders.period}
          />
          <StatCard
            title="Patientèles"
            value={data.patients.value.toString()}
            subtitle={data.patients.subtitle}
            change={data.patients.change}
            period={data.patients.period}
          />
        </div>

        {/* Charts */}
        <div className="grid grid-cols-2 gap-6">
          {data.pharmacyOrders && <PharmacyBarChart data={data.pharmacyOrders} />}
          {data.zoneDistribution && <ZonePieChart data={data.zoneDistribution} />}
        </div>
      </main>
    </div>
  );
}

// resources/js/pages/Dashboard.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { Head, router } from '@inertiajs/vue3';
import { usePolling } from '@/composables/usePolling';
import {
    ArrowDownRight,
    ArrowUpRight,
    ChevronDown,
    Pill,
} from 'lucide-vue-next';
import AppLayout from '@/layouts/AppLayout.vue';
import type { BreadcrumbItem } from '@/types';
import { dashboard } from '@/routes';
import { usePage } from '@inertiajs/vue3';

usePolling();

const page = usePage();
const roles = computed(() => (page.props.auth as { user?: { roles?: string[] } })?.user?.roles ?? []);
const isPharma = computed(() => roles.value.includes('gerant') || roles.value.includes('vendeur'));

const periodDropdownOpen = ref(false);

const props = defineProps<{
    period?: string;
    kpis: {
        revenuTotal: number;
        nbPharmacies: number;
        nbCommandes: number;
        nbClients: number;
        evolutionRevenu: number;
        evolutionPharmacies: number;
        evolutionCommandes: number;
        evolutionClients: number;
    };
    volumeParPharmacie: Array<{ pharmacie: { designation: string } | null; total: number }>;
    volumeParZone: Array<{ zone_name: string; total: number }>;
    revenusParJour?: Array<{ jour: string; label: string; total: number }>;
}>();

const period = computed(() => props.period ?? 'month');

function setPeriod(p: string) {
    periodDropdownOpen.value = false;
    router.get(dashboard(), { period: p }, { preserveState: true });
}

const breadcrumbs: BreadcrumbItem[] = [
    { title: 'Tableau de bord', href: dashboard() },
];

// Couleurs des zones (design Figma)
const zoneColors = [
    '#3995D2',  // Bleu - Moungali
    '#DC3545',  // Rouge - Poto-Poto
    '#FD7E14',  // Orange - Bacongo
    '#FFC107',  // Jaune - Makélékélé
    '#198754',  // Vert - Ouenzé
    '#8a38f5',  // Violet - Mfilou (Figma)
];

const heroIcons = [
    { src: '/images/figma-assets/hero-icon-1.png', class: 'absolute right-[15%] -top-12 w-[140px] h-[140px] object-contain rotate-[4deg]' },
    { src: '/images/figma-assets/hero-icon-2.png', class: 'absolute right-[5%] top-2 w-[120px] h-[120px] object-contain -rotate-[17deg]' },
    { src: '/images/figma-assets/hero-icon-3.png', class: 'absolute right-[25%] top-4 w-[100px] h-[100px] object-contain rotate-[27deg]' },
    { src: '/images/figma-assets/hero-icon-4.png', class: 'absolute right-[12%] top-16 w-[130px] h-[130px] object-contain rotate-[12deg]' },
    { src: '/images/figma-assets/hero-icon-5.png', class: 'absolute right-[35%] -top-8 w-[180px] h-[180px] object-contain -rotate-[9deg]' },
    { src: '/images/figma-assets/hero-icon-6.png', class: 'absolute right-[20%] top-20 w-[150px] h-[150px] object-contain rotate-[10deg]' },
];

const volumeParZoneWithPercent = computed(() => {
    const total = props.volumeParZone.reduce((a, z) => a + z.total, 0) || 1;
    let currentAngle = 0;
    return props.volumeParZone.map((z, i) => {
        const percent = Math.round((z.total / total) * 100);
        const angle = (percent / 100) * 360;
        const startAngle = currentAngle;
        currentAngle += angle;
        return {
            ...z,
            percent,
            color: zoneColors[i % zoneColors.length],
            startAngle,
            angle,
        };
    });
});

const maxVolume = computed(() =>
    Math.max(...props.volumeParPharmacie.map((v) => v.total), 1)
);

const barChartScaleLabels = computed(() => {
    const max = maxVolume.value;
    if (max <= 0) return ['0'];
    const step = Math.max(1, Math.ceil(max / 5));
    const labels = [5 * step, 4 * step, 3 * step, 2 * step, step].filter((v) => v <= max);
    return labels.length > 0 ? labels : [max];
});

const revenusParJour = computed(() => props.revenusParJour ?? []);
const maxRevenuJour = computed(() =>
    Math.max(...revenusParJour.value.map((r) => r.total), 1)
);
const revenusScaleLabels = computed(() => {
    const max = maxRevenuJour.value;
    if (max <= 0) return ['0'];
    const step = Math.max(1, Math.ceil(max / 5));
    const labels = [5 * step, 4 * step, 3 * step, 2 * step, step].filter((v) => v <= max);
    return labels.length > 0 ? labels : [max];
});

function formatRevenuShort(val: number): string {
    if (val >= 1_000_000) return `${Math.round(val / 1_000_000)}M`;
    if (val >= 1_000) return `${Math.round(val / 1_000)}K`;
    return String(Math.round(val));
}

// Génère le path SVG pour un segment du diagramme circulaire (style Doughnut/Pie)
function getPiePath(
    cx: number,
    cy: number,
    radius: number,
    startAngle: number,
    endAngle: number,
    strokeWidth: number = 0
) {
    const startRad = (startAngle * Math.PI) / 180;
    const endRad = (endAngle * Math.PI) / 180;
    
    // Si c'est un Doughnut (strokeWidth > 0), le calcul se fait sur le centre du trait
    const effectiveRadius = strokeWidth > 0 ? radius - (strokeWidth / 2) : radius;
    
    const x1 = cx + effectiveRadius * Math.cos(startRad);
    const y1 = cy + effectiveRadius * Math.sin(startRad);
    const x2 = cx + effectiveRadius * Math.cos(endRad);
    const y2 = cy + effectiveRadius * Math.sin(endRad);
    
    const largeArc = endAngle - startAngle > 180 ? 1 : 0;
    
    // Si c'est un Doughnut (uniquement le trait, pas de remplissage)
    if (strokeWidth > 0) {
        return `M ${x1} ${y1} A ${effectiveRadius} ${effectiveRadius} 0 ${largeArc} 1 ${x2} ${y2}`;
    }
    
    // Sinon c'est un Pie classique (rempli jusqu'au centre)
    return `M ${cx} ${cy} L ${x1} ${y1} A ${effectiveRadius} ${effectiveRadius} 0 ${largeArc} 1 ${x2} ${y2} Z`;
}
</script>

<template>
    <Head title="Tableau de bord - BengaDok" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="relative min-h-full overflow-x-auto rounded-xl p-6 md:p-8">
            <!-- Hero section Admin - style Figma -->
            <div
                v-if="!isPharma"
                class="relative mb-6 overflow-hidden rounded-[30px] bg-white shadow-[0px_4px_10px_rgba(0,0,0,0.25)] min-h-[257px] flex items-center px-8 md:px-10 py-8"
            >
                <h1 class="relative z-20 max-w-[473px] text-[40px] md:text-[55px] font-extrabold leading-tight text-[#5c5959] drop-shadow-[4px_4px_20px_rgba(0,0,0,0.25)]">
                    Toutes les données au même endroit
                </h1>
                <!-- Icônes 3D flottantes Figma -->
                <div class="absolute inset-0 pointer-events-none hidden lg:block">
                    <img
                        v-for="(icon, i) in heroIcons"
                        :key="i"
                        :src="icon.src"
                        :class="icon.class"
                        alt=""
                    />
                </div>
            </div>

            <!-- Hero section Pharma -->
            <div
                v-if="isPharma"
                class="relative mb-6 overflow-hidden rounded-[30px] bg-white p-8 shadow-[0px_4px_10px_rgba(0,0,0,0.25)] flex items-center justify-between min-h-[220px]"
            >
                <h1
                    class="relative z-10 max-w-[450px] text-[40px] font-bold leading-tight text-[#5c5959] md:text-[44px]"
                >
                    Créez de la proximité avec votre patientèle
                </h1>
                
                <div class="absolute right-0 top-0 bottom-0 w-[60%] pointer-events-none hidden md:flex justify-end items-end gap-2 pr-8">
                     <img src="/images/pharma-banner-3.png" class="h-[90%] object-contain -mb-2 z-20" alt="" />
                     <img src="/images/pharma-banner-2.png" class="h-full object-contain z-10" alt="" />
                </div>
            </div>

            <!-- Sélecteur de période global -->
            <div class="mb-4 flex justify-end">
                <div class="relative">
                    <button
                        class="flex items-center gap-2 rounded-[13px] border border-gray-300 bg-white px-4 py-2 text-[14px] font-semibold text-gray-800 shadow-sm hover:bg-gray-50"
                        @click="periodDropdownOpen = !periodDropdownOpen"
                    >
                        {{ period === 'week' ? 'Cette semaine' : 'Ce mois' }}
                        <ChevronDown class="size-4" />
                    </button>
                    <div
                        v-show="periodDropdownOpen"
                        class="absolute right-0 top-full z-20 mt-1 min-w-[160px] rounded-lg border border-gray-200 bg-white py-1 shadow-lg"
                    >
                        <button
                            class="w-full px-4 py-2 text-left text-[14px] hover:bg-gray-100"
                            @click="setPeriod('week')"
                        >
                            Cette semaine
                        </button>
                        <button
                            class="w-full px-4 py-2 text-left text-[14px] hover:bg-gray-100"
                            @click="setPeriod('month')"
                        >
                            Ce mois
                        </button>
                    </div>
                </div>
            </div>

            <!-- Stats cards Admin - style Figma -->
            <div v-if="!isPharma" class="mb-6 grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
                <div class="rounded-[23px] bg-white p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.25)] relative overflow-hidden group hover:shadow-lg transition-shadow">
                    <h3 class="mb-6 text-[14px] font-extrabold text-[#5c5959]">Revenue Total Comission</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[32px] font-extrabold text-black">{{ Number(kpis.revenuTotal).toLocaleString('fr-FR') }}</span>
                        <span class="text-[14px] font-bold text-black">XAF</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 rounded-full border border-black/20 px-2 py-1" :class="kpis.evolutionRevenu >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionRevenu >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionRevenu) }}%
                        </span>
                        <span class="text-[#5c5959]">Depuis cette semaine</span>
                    </div>
                </div>

                <div class="rounded-[23px] bg-white p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.25)] relative overflow-hidden group hover:shadow-lg transition-shadow">
                    <h3 class="mb-6 text-[14px] font-extrabold text-[#5c5959]">Pharmacies</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[32px] font-extrabold text-black">{{ kpis.nbPharmacies }}</span>
                        <span class="text-[14px] font-bold text-black">Pharmacies de Jour</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 rounded-full border border-black/20 px-2 py-1" :class="kpis.evolutionPharmacies >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionPharmacies >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionPharmacies) }}%
                        </span>
                        <span class="text-[#5c5959]">Depuis cette semaine</span>
                    </div>
                </div>

                <div class="rounded-[23px] bg-white p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.25)] relative overflow-hidden group hover:shadow-lg transition-shadow">
                    <h3 class="mb-6 text-[14px] font-extrabold text-[#5c5959]">Commandes Total</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[32px] font-extrabold text-black">{{ kpis.nbCommandes }}</span>
                        <span class="text-[14px] font-bold text-black">cmd</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 rounded-full border border-black/20 px-2 py-1" :class="kpis.evolutionCommandes >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionCommandes >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionCommandes) }}%
                        </span>
                        <span class="text-[#5c5959]">Depuis cette semaine</span>
                    </div>
                </div>

                <div class="rounded-[23px] bg-white p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.25)] relative overflow-hidden group hover:shadow-lg transition-shadow">
                    <h3 class="mb-6 text-[14px] font-extrabold text-[#5c5959]">Patientèles</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[32px] font-extrabold text-black">{{ kpis.nbClients }}</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 rounded-full border border-black/20 px-2 py-1" :class="kpis.evolutionClients >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionClients >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionClients) }}%
                        </span>
                        <span class="text-[#5c5959]">Depuis cette semaine</span>
                    </div>
                </div>
            </div>

            <!-- Stats cards Pharmacie -->
            <div v-if="isPharma" class="mb-6 grid gap-4 grid-cols-1 sm:grid-cols-3">
                <div class="rounded-[20px] bg-[#E1EFE8] backdrop-blur-sm p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.1)] relative transition-transform hover:-translate-y-1">
                    <h3 class="mb-6 text-[15px] font-bold text-gray-900">Revenue Total</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[36px] font-bold text-gray-900">{{ Number(kpis.revenuTotal).toLocaleString('fr-FR') }}</span>
                        <span class="text-[14px] font-bold text-gray-900">XAF</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 bg-white rounded-full px-2 py-1 shadow-sm" :class="kpis.evolutionRevenu >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionRevenu >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionRevenu) }}%
                        </span>
                        <span class="text-gray-800">Depuis cette semaine</span>
                    </div>
                </div>

                <div class="rounded-[20px] bg-[#E1EFE8] backdrop-blur-sm p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.1)] relative transition-transform hover:-translate-y-1">
                    <h3 class="mb-6 text-[15px] font-bold text-gray-900">Commande Total</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[36px] font-bold text-gray-900">{{ kpis.nbCommandes }}</span>
                        <span class="text-[14px] font-bold text-gray-900">Cmd</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 bg-white rounded-full px-2 py-1 shadow-sm" :class="kpis.evolutionCommandes >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionCommandes >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionCommandes) }}%
                        </span>
                        <span class="text-gray-800">Depuis cette semaine</span>
                    </div>
                </div>

                <div class="rounded-[20px] bg-[#E1EFE8] backdrop-blur-sm p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.1)] relative transition-transform hover:-translate-y-1">
                    <h3 class="mb-6 text-[15px] font-bold text-gray-900">Client Total</h3>
                    <div class="mb-4 flex items-baseline gap-2">
                        <span class="text-[36px] font-bold text-gray-900">{{ kpis.nbClients }}</span>
                        <span class="text-[14px] font-bold text-gray-900">Clients</span>
                    </div>
                    <div class="flex items-center gap-2 text-[11px] font-semibold">
                        <span class="flex items-center gap-1 bg-white rounded-full px-2 py-1 shadow-sm" :class="kpis.evolutionClients >= 0 ? 'text-black' : 'text-red-600'">
                            <ArrowUpRight v-if="kpis.evolutionClients >= 0" class="size-3" />
                            <ArrowDownRight v-else class="size-3" />
                            {{ Math.abs(kpis.evolutionClients) }}%
                        </span>
                        <span class="text-gray-800">Depuis cette semaine</span>
                    </div>
                </div>
            </div>

            <!-- Charts Admin - style Figma -->
            <div v-if="!isPharma" class="grid gap-6 lg:grid-cols-2">
                <!-- Volume commandes par pharmacies (bar chart) -->
                <div
                    class="rounded-[30px] bg-white p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.25)]"
                >
                    <div class="mb-6 flex items-center justify-between">
                        <h3 class="text-[20px] font-bold text-black">
                            Volume commandes par pharmacies
                        </h3>
                        <span class="rounded-[13px] border border-black/30 bg-gray-50 px-3 py-1 text-[14px] font-semibold text-gray-700">
                            {{ period === 'week' ? 'Cette semaine' : 'Ce mois' }}
                        </span>
                    </div>
                    <div
                        class="relative flex items-end justify-around gap-3 px-4"
                        style="height: 300px"
                    >
                        <div
                            class="absolute left-0 top-0 flex flex-col justify-between text-[12px] text-gray-600"
                            style="bottom: 2rem"
                        >
                            <span v-for="label in barChartScaleLabels" :key="label">{{ label }}</span>
                        </div>
                        <div
                            class="ml-8 flex flex-1 items-end justify-around gap-3"
                        >
                            <div
                                v-for="(item, i) in volumeParPharmacie"
                                :key="i"
                                class="flex flex-1 flex-col items-center"
                            >
                                <div
                                    class="w-3 rounded-t-[3px] bg-[#5bb66e] transition-all hover:bg-[#4ca55d] min-w-[12px]"
                                    :style="{
                                        height: `${
                                            (item.total / maxVolume) * 250
                                        }px`,
                                        minHeight:
                                            item.total > 0 ? '8px' : '0',
                                    }"
                                />
                                <span
                                    class="mt-2 w-full truncate whitespace-nowrap text-center text-[10px] text-gray-700"
                                    :title="item.pharmacie?.designation"
                                >
                                    {{ item.pharmacie?.designation ?? 'N/A' }}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Volume commandes par zone (pie chart) -->
                <div class="rounded-[30px] bg-white p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.25)]">
                    <div class="mb-6 flex items-center justify-between">
                        <h3 class="text-[20px] font-bold text-black">Volume commandes par zone</h3>
                        <span class="rounded-[13px] border border-black/30 bg-gray-50 px-3 py-1 text-[14px] font-semibold text-gray-700">
                            {{ period === 'week' ? 'Cette semaine' : 'Ce mois' }}
                        </span>
                    </div>
                    
                    <div class="flex flex-col lg:flex-row items-center lg:items-start gap-6 mt-6">
                        <!-- Graphique donut à gauche -->
                        <div class="relative size-[180px] shrink-0">
                            <svg viewBox="0 0 200 200" class="size-full -rotate-90">
                                <circle cx="100" cy="100" r="75" fill="none" stroke="#f3f4f6" stroke-width="25" />
                                <path
                                    v-for="(zone, i) in volumeParZoneWithPercent"
                                    v-show="zone.percent > 0"
                                    :key="zone.zone_name"
                                    :d="
                                        getPiePath(
                                            100,
                                            100,
                                            100,
                                            zone.startAngle,
                                            zone.startAngle + zone.angle,
                                            25
                                        )
                                    "
                                    fill="none"
                                    :stroke="zone.color"
                                    stroke-width="25"
                                    class="transition-opacity hover:opacity-80"
                                />
                            </svg>
                            <div class="absolute inset-0 flex flex-col items-center justify-center">
                                <div class="flex size-[54px] items-center justify-center rounded-full bg-[#f3f4f6]">
                                    <Pill class="size-6 text-[#3995D2]" />
                                </div>
                            </div>
                        </div>
                        <!-- Légende avec barres de progression à droite -->
                        <div class="flex flex-1 flex-col gap-4 min-w-0">
                            <div
                                v-for="(zone, i) in volumeParZoneWithPercent"
                                :key="zone.zone_name"
                                class="flex items-center gap-3 w-full"
                            >
                                <span class="text-[13px] font-bold truncate shrink-0" :style="{ color: zone.color }">
                                    {{ zone.zone_name }}
                                </span>
                                <div class="flex-1 h-[5px] min-w-0 rounded-full bg-[rgba(102,102,102,0.42)] overflow-hidden">
                                    <div
                                        class="h-full rounded-full transition-all"
                                        :style="{
                                            width: `${zone.percent}%`,
                                            backgroundColor: zone.color,
                                        }"
                                    />
                                </div>
                                <span class="text-[13px] font-bold shrink-0" :style="{ color: zone.color }">
                                    {{ zone.percent }}%
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Charts Pharmacie -->
            <div v-if="isPharma">
                <div class="rounded-[30px] bg-[#E1EFE8] backdrop-blur-sm p-6 shadow-[0px_4px_10px_rgba(0,0,0,0.1)] w-full relative">
                    <div class="mb-6 flex items-center justify-between">
                        <h3 class="text-[20px] font-extrabold text-gray-900">Analyse revenues</h3>
                        <span class="rounded-full border border-gray-400 bg-white/80 px-4 py-1.5 text-[13px] font-bold text-gray-900">
                            {{ period === 'week' ? 'Cette semaine' : 'Ce mois' }}
                        </span>
                    </div>
                    <!-- Chart barres revenues -->
                    <div class="flex items-end px-2 pt-2 gap-2 lg:gap-4 relative h-[250px] mt-4 w-full">
                        <div class="flex flex-col justify-between text-[11px] font-bold text-gray-600 h-full pb-6">
                            <span v-for="label in revenusScaleLabels" :key="label">{{ formatRevenuShort(label) }}</span>
                        </div>
                        
                        <!-- Barres -->
                        <div class="flex flex-1 items-end justify-between ml-4 h-[250px] pb-[1.75rem]">
                            <div
                                v-for="(item, i) in revenusParJour"
                                :key="item.jour"
                                class="flex flex-col items-center flex-1 mx-1 gap-2 h-full justify-end"
                            >
                                <div class="relative w-full max-w-[50px] h-full bg-[#d0e6d9] rounded-[24px] overflow-hidden flex items-end opacity-80 group cursor-pointer">
                                    <div
                                        class="w-full bg-[#5BB66E] rounded-[24px] transition-all duration-300 group-hover:bg-[#4a975a]"
                                        :style="{ height: `${((item.total || 0) / (maxRevenuJour || 1)) * 100}%` }"
                                    />
                                </div>
                                <span class="text-[13px] font-bold text-gray-700 mt-2">{{ item.label }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </AppLayout>
</template>
